Update main.yml
updated newman reporting command

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -35,7 +35,9 @@ jobs:
         npm install -g newman-reporter-junitxray
 
     - name: Run Newman
-      run: newman run CVC_Apis.postman_collection.json -r 'cli,junitfull,junitxray' --reporter-junitfull-export cvc_junitfull.xml
+      id: newman
+      run: newman run CVC_Apis.postman_collection.json -r 'cli,junitfull,junitxray' --reporter-junitfull-export cvc_junitfull.xml || echo "::set-output name=failed::true"
+      continue-on-error: true
       
     - name: Upload newman report as artifact
       if: steps.newman.outputs.failed == 'true'
