Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,7 +36,7 @@ jobs:
 
     - name: Run Newman
       id: newman
-      run: newman run CVC_Apis.postman_collection.json --reporters junitfull --reporter-junitfull-export junit-report.xml || echo "::set-output name=failed::true"
+      run: newman run CVC_Apis.postman_collection.json --reporters junitfull --reporter-junitfull-export /home/runner/work/postman-newman/postman-newman/junit-report.xml || echo "::set-output name=failed::true"
       continue-on-error: true
     - name: Check directory
       run: |
@@ -48,13 +48,13 @@ jobs:
       uses: actions/upload-artifact@v2
       with:
         name: junit-report
-        path: junit-report.xml
+        path: /home/runner/work/postman-newman/postman-newman/junit-report.xml
         
     - name: Download report artifact
       uses: actions/download-artifact@v2
       with:
         name: junit-report
-        path: junit-report.xml
+        path: /home/runner/work/postman-newman/postman-newman/junit-report.xml
         
         
   job3:
@@ -76,7 +76,7 @@ jobs:
       - name: Use Token in Curl Command
         
         run: |
-          curl -H 'Content-Type: text/xml' -X POST -H "Authorization: Bearer $TOKEN" --data @junit-report.xml https://xray.cloud.getxray.app/api/v2/import/execution/junit?projectKey=CQ
+          curl -H 'Content-Type: text/xml' -X POST -H "Authorization: Bearer $TOKEN" --data @/home/runner/work/postman-newman/postman-newman/junit-report.xml https://xray.cloud.getxray.app/api/v2/import/execution/junit?projectKey=CQ
       - name: Check directory
         run: |
             pwd
