Update main.yml
updated job2

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,15 +36,16 @@ jobs:
 
     - name: Run Newman
       id: newman
-      run: newman run CVC_Apis.postman_collection.json -r 'cli,junitfull,junitxray' --reporter-junitfull-export cvc_junitfull.xml || echo "::set-output name=failed::true"
+      run: newman run CVC_Apis.postman_collection.json -r junitfull --reporter-junitfull-export reports/result.xml || echo "::set-output name=failed::true"
       continue-on-error: true
       
-    - name: Upload newman report as artifact
+    - name: Upload JUnit report
       if: steps.newman.outputs.failed == 'true'
       uses: actions/upload-artifact@v2
       with:
-        name: newman-report
-        path: reports/cvc_junitfull.xml
+        name: junit-report
+        path: reports/result.xml
+
 
       
   job3:
@@ -65,7 +66,7 @@ jobs:
         env:
             TOKEN: ${{ secrets.TOKEN }}
         run: |
-          curl -H 'Content-Type: text/xml' -X POST -H "Authorization': ${TOKEN}" --data @${{ github.workspace }}/reports/cvc_junitfull.xml https://xray.cloud.getxray.app/api/v2/import/execution/junit?projectKey=CQ
+          curl -H 'Content-Type: text/xml' -X POST -H "Authorization': ${TOKEN}" --data @reports/result.xml https://xray.cloud.getxray.app/api/v2/import/execution/junit?projectKey=CQ
         
         
     
